import logo from "../assets/logo.svg"
import rentbanner from "../assets/rentbanner.svg"
import metamask from "../assets/metamask.svg"
import mbtoken from "../assets/mbtoken.svg"
import opensea from "../assets/opensea.svg"
import nft0 from "../assets/nft0.svg"
import nft1 from "../assets/nft1.svg"
import nft2 from "../assets/nft2.svg"
import nft3 from "../assets/nft3.svg"
import nft4 from "../assets/nft4.svg"
import nft5 from "../assets/nft5.svg"
import nft6 from "../assets/nft6.svg"
import nft7 from "../assets/nft7.svg"
import nft8 from "../assets/nft8.svg"
import nft9 from "../assets/nft9.svg"
import nft10 from "../assets/nft10.svg"
import nft11 from "../assets/nft11.svg"
import nft12 from "../assets/nft12.svg"
import nft13 from "../assets/nft13.svg"
import nft14 from "../assets/nft14.svg"
import nft15 from "../assets/nft15.svg"
import star from "../assets/star.svg"
import footerbanner from "../assets/footerbanner.svg"
import footerlogo from "../assets/footerlogo.svg"
import metamasklogo from "../assets/metamask.png"
import wallet from "../assets/wallet.png"


const images = {wallet, metamasklogo, logo, rentbanner, metamask, mbtoken, opensea,nft0 ,nft1 ,nft2 ,nft3 ,nft4 ,nft5,nft6 ,nft7, nft8, nft9, nft10, nft11, nft12, nft13, nft14, nft15, star, footerbanner, footerlogo}
export default images;